'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {BookOpen,ExternalLink,Info,Search,RefreshCw,ArrowUpRight,ArrowDownRight} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {constitutionalLaws,crimeLaws,sources,type Law} from '@/lib/legal-data';
import national from '@/lib/national-crime.json';
import type {AskAnswer,Citation} from '@/lib/ask';
function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker" aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o} value={o}>{o}</SelectItem>)}</SelectContent></Select>}
function CitationText({text,citations}:{text:string;citations:Citation[]}){let cursor=0;const parts:ReactNode[]=[];[...citations].sort((a,b)=>a.start-b.start).forEach((c,i)=>{if(c.start<cursor)return;parts.push(text.slice(cursor,c.start));parts.push(<a key={`${c.start}-${i}`} href={c.url} target="_blank" rel="noreferrer" className="inline-cite" title={c.title}>{text.slice(c.start,c.end)||`[${i+1}]`}</a>);cursor=c.end});parts.push(text.slice(cursor));return <p className="answertext">{parts}</p>}
export function ApiAnswerPanel({answer,busy,error,onOpen}:{answer:AskAnswer|null;busy:boolean;error:string;onOpen:(l:Law)=>void}){
 if(!answer&&!busy&&!error)return null;
 return <section className="surface apianswer" id="api-answer" aria-live="polite" aria-busy={busy}><div className="eyebrow">ASK YOUR SITUATION · SERVER API</div><h2>{busy?'Finding your legal starting point…':answer?.mode==='ai'?'Your source-grounded explanation':'Official-source matches'}</h2>{busy&&<p>Checking the relevant provisions and available sources.</p>}{error&&<div className="notice warning"><Info size={18}/>{error}</div>}{answer&&!busy&&<><div className="statuspill">{answer.mode==='ai'?'AI + official web sources':'Curated retrieval · AI not used'}</div><p>{answer.message}</p>{answer.warning&&<div className="notice warning"><Info size={18}/>{answer.warning}</div>}{answer.context.region&&<p className="smallnote">Location: {answer.context.region}. State-specific applicability must be checked. {answer.context.incidentDate&&`Incident date: ${answer.context.incidentDate}.`}</p>}{answer.generated?.map((p,i)=><CitationText key={i} {...p}/>)}{answer.references.length>0&&<><h3>Official wording & plain meaning</h3><div className="answerrefs">{answer.references.map(l=><article key={l.id}><span className="tag">{l.ref}</span><h4>{l.title}</h4><blockquote>“{l.quote}”</blockquote><p><strong>Plain meaning:</strong> {l.meaning}</p><p className="smallnote">{l.note}</p><div className="quoteactions"><a className="out" href={sources[l.source].url} target="_blank" rel="noreferrer">Official source <ExternalLink size={13}/></a><button className="textbutton" onClick={()=>onOpen(l)}>Read context</button></div></article>)}</div></>}<p className="smallnote">Original excerpts: linked official publications. Explanations: Nyaya editorial content{answer.mode==='ai'?' and AI-generated text':''}. Source collection reviewed {answer.reviewed}. Legal information; a lawyer should assess your case.</p></>}</section>
}
export function RightsAtlas({onOpen,onFilter}:{onOpen:(l:Law)=>void;onFilter:(s:string)=>void}){
 const [part,setPart]=useState('Part III · fundamental rights');
 const key=part.startsWith('Part III')?'III':part.startsWith('Part IV')?'IV':'Other';
 const list=constitutionalLaws.filter(l=>l.part===key);
 return <section className="rights-atlas surface"><div className="sectionline"><div><div className="eyebrow">THE CONSTITUTION, MAPPED</div><h2>Your rights atlas</h2></div><Choice value={part} onChange={setPart} options={['Part III · fundamental rights','Part IV · Directive Principles','Other constitutional safeguards']} label="Constitution part"/></div><p>{key==='III'?'Every Part III article is indexed here, including qualifications, remedies and omitted provisions. The main rights span equality, freedom, protection from exploitation, religion, culture and education.':key==='IV'?'Every Part IV article is indexed. These principles guide the State; Article 37 says they are not directly enforceable by courts.':'Further constitutional protections and emergency qualifications. This collection does not claim to index every statutory or state-law entitlement.'}</p><div className="articlemap">{list.map(l=><button key={l.id} onClick={()=>onOpen(l)} className={l.group==='Omitted provisions'?'omitted':''} title={l.title}><strong>{l.article}</strong><span>{l.group==='Omitted provisions'?'Omitted':l.group}</span></button>)}</div><div className="rights-legend"><span>{list.length} article entries</span><button className="textbutton" onClick={()=>onFilter(key==='IV'?'Directive Principles':key==='Other'?'Other constitutional protections':'All topics')}>Browse provision cards ↓</button><a className="out" href={sources.constitution.url} target="_blank" rel="noreferrer">Read full Constitution <ExternalLink size={13}/></a></div></section>
}
export function CrimeCatalogue({onOpen}:{onOpen:(l:Law)=>void}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState('All crime families');
 const entries=crimeLaws.filter(l=>(category==='All crime families'||l.category===category)&&`${l.ref} ${l.title} ${l.meaning} ${l.keywords}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="subsection"><div className="pageheading"><div className="eyebrow">OFFENCE REFERENCE INDEX</div><h1>Understand the types of crime.</h1><p>48 BNS offence entries, organised by topic. Each links an official heading to its plain meaning and legal conditions.</p></div><div className="notice"><Info size={18}/><span>An index entry is not a charge or finding of guilt. BNS generally commenced on 1 July 2024 with exceptions. Earlier incidents and special laws need separate checks. The statistical categories below are not a one-to-one mapping to BNS sections.</span></div><div className="filterbar"><label className="searchbox"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search crime, section or situation…" aria-label="Search crime index"/></label><Choice value={category} onChange={setCategory} options={['All crime families',...new Set(crimeLaws.map(l=>l.category))]} label="Crime family"/></div><div className="resultmeta">{entries.length} entries · Official BNS Gazette · Click an entry to read its source</div><div className="source-table"><Table><TableHeader><TableRow><TableHead>Section index</TableHead><TableHead>Offence / provision</TableHead><TableHead>Crime family</TableHead><TableHead>Plain meaning</TableHead></TableRow></TableHeader><TableBody>{entries.map(l=><TableRow key={l.id}><TableCell><button className="textbutton" onClick={()=>onOpen(l)}>{l.ref}</button></TableCell><TableCell><button className="crime-title" onClick={()=>onOpen(l)}>{l.title}</button></TableCell><TableCell>{l.category}</TableCell><TableCell>{l.meaning}</TableCell></TableRow>)}</TableBody></Table></div>{!entries.length&&<p className="empty">No matching entry in this index. Search the complete India Code for other provisions.</p>}<div className="special-laws"><h3>Special-law routes</h3><p>Some conduct is addressed by other legislation. Use the full official Act and a lawyer to identify the relevant provision.</p><div className="chips">{[['NDPS · drugs and controlled substances',sources.ndps.url],['Information Technology Act · digital offences',sources.it.url],['Domestic Violence Act · protection and relief',sources.dv.url],['Other Acts · POCSO, SC/ST atrocities, Arms, UAPA, corruption', 'https://www.indiacode.nic.in/']].map(([t,u])=><a key={t} href={u} target="_blank" rel="noreferrer">{t} <ExternalLink size={12}/></a>)}</div></div></section>
}
export function NationalTrends(){
 const [selected,setSelected]=useState(national.series[0].name);
 const series=national.series.find(s=>s.name===selected)!; const [a,b,c]=series.values;const change=(c-b)/b*100;
 return <section className="surface national-trends"><div className="sectionline"><div><div className="eyebrow">NCRB · NATIONAL STATISTICS</div><h2>A broader view of recorded crime</h2></div><Choice value={selected} onChange={setSelected} options={national.series.map(s=>s.name)} label="National crime category"/></div><p>Verified historical series · 2020–2022 · Published in the MHA Annual Report 2024–25. Newer reporting years may exist; this series is kept separate from the cybercrime feed below.</p><div className="statgrid"><div className="stat"><span>2022 · registered cases</span><strong>{c.toLocaleString('en-IN')}</strong><small>{selected}</small></div><div className="stat"><span>2022 compared with 2021</span><strong>{change>=0?<ArrowUpRight/>:<ArrowDownRight/>}{Math.abs(change).toFixed(1)}%</strong><small>{change>=0?'Increase':'Decrease'} in registered cases</small></div><div className="stat"><span>2020 · baseline</span><strong>{a.toLocaleString('en-IN')}</strong><small>Count, not a population-adjusted rate</small></div></div><div className="trendbars" role="img" aria-label={`${selected}: ${national.years.map((y,i)=>`${y}: ${series.values[i]} cases`).join('; ')}`}>{series.values.map((v,i)=><div key={i}><span>{national.years[i]}</span><div><i style={{width:`${v/Math.max(...series.values)*100}%`}}/></div><strong>{v.toLocaleString('en-IN')}</strong></div>)}</div><details className="all-statistics"><summary>View all categories and annual changes</summary><div className="source-table"><Table><TableHeader><TableRow><TableHead>Crime category</TableHead>{national.years.map(y=><TableHead key={y}>{y}</TableHead>)}<TableHead>2021 → 2022</TableHead></TableRow></TableHeader><TableBody>{national.series.map(s=><TableRow key={s.name}><TableCell>{s.name}</TableCell>{s.values.map((v,i)=><TableCell key={i}>{v.toLocaleString('en-IN')}</TableCell>)}<TableCell>{((s.values[2]-s.values[1])/s.values[1]*100).toFixed(1)}%</TableCell></TableRow>)}</TableBody></Table></div></details><a className="out" href={national.sourceUrl} target="_blank" rel="noreferrer">{national.sourceTitle} <ExternalLink size={13}/></a><p className="smallnote">Categories overlap and must not be added together. Registered cases are not convictions. Reporting, population and classification changes affect comparisons. The source uses IPC-era categories; no unsupported conversion to BNS has been made.</p></section>
}
export function ApiConnections(){
 const [ask,setAsk]=useState<{mode:string}|null>(null),[ogd,setOgd]=useState<{status:string;message?:string;title?:string;sourceUrl?:string;records?:Record<string,unknown>[];note?:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){setBusy(true);setError('');try{const [a,b]=await Promise.all([fetch('/api/ask').then(r=>r.json() as Promise<{mode:string}>),fetch('/api/data-gov').then(r=>r.json() as Promise<NonNullable<typeof ogd>>)]);setAsk(a);setOgd(b)}catch{setError('Connection status is unavailable. Try again.')}finally{setBusy(false)}}
 useEffect(()=>{void refresh()},[]);
 const columns=ogd?.records?.length?Object.keys(ogd.records[0]).slice(0,8):[];
 return <section className="surface subsection"><div className="sectionline"><div><div className="eyebrow">LIVE CONNECTION STATUS</div><h2>Situation API & government data</h2></div><button className="secondary" onClick={()=>void refresh()} disabled={busy}><RefreshCw size={15}/>{busy?'Checking…':'Check connections'}</button></div>{error&&<p role="alert">{error}</p>}<div className="connection-grid"><article><h3>Ask your situation</h3><span className="statuspill">{ask?ask.mode==='ai'?'AI configured · official-source search':'API active · curated retrieval':'Checking status'}</span><p>Requests are processed by the server. With an OpenAI key configured, answers use web search limited to official Indian sources and show linked citations. If that service fails, curated matches remain available.</p></article><article><h3>Open Government Data</h3><span className="statuspill">{ogd?.status||'Checking status'}</span><p>{ogd?.message||ogd?.note||'Retrieves the configured government dataset when API access is available.'}</p></article></div>{ogd?.records&&<details><summary>{ogd.title} · first {ogd.records.length} records</summary><p className="smallnote">These are source records, not an automatically reconciled crime series.</p>{ogd.sourceUrl&&<a className="out" href={ogd.sourceUrl} target="_blank" rel="noreferrer">Official OGD resource <ExternalLink size={13}/></a>}<div className="source-table"><Table><TableHeader><TableRow>{columns.map(c=><TableHead key={c}>{c}</TableHead>)}</TableRow></TableHeader><TableBody>{ogd.records.map((r,i)=><TableRow key={i}>{columns.map(c=><TableCell key={c}>{typeof r[c]==='object'?JSON.stringify(r[c]):String(r[c]??'—')}</TableCell>)}</TableRow>)}</TableBody></Table></div></details>}</section>
}
