import constitutionalEntries from './constitution.json';
import crimeEntries from './crime-catalogue.json';
export const REVIEWED = '2 October 2026';
export const sources = {
 constitution:{name:'Legislative Department · Constitution of India',url:'https://www.legislative.gov.in/static/uploads/2025/07/ca7ce5c746fa7480804bbdeb6cb704f0.pdf',edition:'Official bilingual edition, as on 1 May 2024'},
 bnss:{name:'Ministry of Home Affairs · BNSS, 2023',url:'https://www.mha.gov.in/sites/default/files/2024-04/250884_2_english_01042024.pdf',edition:'Gazette of India · Act 46 of 2023'},
 bns:{name:'Ministry of Home Affairs · BNS, 2023',url:'https://www.mha.gov.in/sites/default/files/250883_english_01042024.pdf',edition:'Gazette of India · Act 45 of 2023'},
 mv:{name:'India Code · Motor Vehicles Act, 1988',url:'https://www.indiacode.nic.in/bitstream/123456789/1798/1/198859.pdf',edition:'Consolidated official statutory text'},
 rahat:{name:'MoRTH / PIB · PM RAHAT',url:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2233219',edition:'Official scheme release · 26 February 2026'},
 ndps:{name:'India Code · NDPS Act, 1985',url:'https://www.indiacode.nic.in/bitstream/123456789/18974/1/narcotic-drugs-and-psychotropic-substances-act-1985.pdf',edition:'Consolidated official statutory text'},
 it:{name:'India Code · Information Technology Act, 2000',url:'https://www.indiacode.nic.in/bitstream/123456789/13116/1/it_act_2000_updated.pdf',edition:'Official statutory text · see amendment footnotes'},
 dv:{name:'India Code · Domestic Violence Act, 2005',url:'https://www.indiacode.nic.in/bitstream/123456789/2021/5/A2005-43.pdf',edition:'Official statutory text'},
 consumer:{name:'India Code · Consumer Protection Act, 2019',url:'https://www.indiacode.nic.in/bitstream/123456789/15256/1/eng201935.pdf',edition:'Official statutory text'},
 aid:{name:'NALSA · Legal aid eligibility',url:'https://nalsa.gov.in/about-nalsa/',edition:'Legal Services Authorities Act, 1987 · sections 12–13'},
 nationalCrime:{name:'NCRB / MHA · Annual Report 2024–25',url:'https://www.mha.gov.in/sites/default/files/AREnglish_24032026.pdf',edition:'Chapter IV · printed pages 53–59 · statistics 2020–2022'},
 crime:{name:'NCRB / Ministry of Home Affairs / PIB',url:'https://www.pib.gov.in/PressReleasePage.aspx?PRID=2287039',edition:'National Cyber Crime Data · 21 July 2026 · Annexures I–II'}
};
export type Law={id:string;ref:string;title:string;category:string;source:keyof typeof sources;quote:string;meaning:string;note:string;keywords:string;article?:string;part?:string;group?:string;section?:number};
const baseLaws:Law[]=[
{id:'art21',ref:'Article 21',title:'Life and personal liberty',category:'Constitution',source:'constitution',quote:'No person shall be deprived of his life or personal liberty except according to procedure established by law.',meaning:'Every person has constitutional protection for life and personal liberty. State action affecting either must follow the law.',note:'This is a foundational right, not a promise that every hospital bill is automatically waived.',keywords:'life liberty medical hospital right person'},
{id:'art14',ref:'Article 14',title:'Equality before the law',category:'Constitution',source:'constitution',quote:'The State shall not deny to any person equality before the law or the equal protection of the laws within the territory of India.',meaning:'The State must treat people equally before the law. Whether a distinction is unlawful depends on its legal justification and the facts.',note:'Applies to every person. Specific remedies depend on the action being challenged.',keywords:'equality discrimination unfair government'},
{id:'art20',ref:'Article 20(3)',title:'Protection against self-incrimination',category:'Constitution',source:'constitution',quote:'No person accused of any offence shall be compelled to be a witness against himself.',meaning:'An accused person cannot be compelled to give self-incriminating testimony. Speak to a lawyer about the scope of this protection.',note:'It does not create a general right to obstruct lawful identification, searches or collection of every kind of evidence.',keywords:'arrest police forced confession silence interrogation'},
{id:'art22',ref:'Article 22(1)',title:'Access to a legal practitioner',category:'Constitution',source:'constitution',quote:'nor shall he be denied the right to consult, and to be defended by, a legal practitioner of his choice.',meaning:'An arrested person has the constitutional right to consult and be defended by a lawyer of their choice, subject to the article’s exceptions.',note:'Article 22 contains exceptions, including for preventive detention. Ask a lawyer which framework applies.',keywords:'arrest custody lawyer advocate detained'},
{id:'art32',ref:'Article 32(1)',title:'Remedies for fundamental rights',category:'Constitution',source:'constitution',quote:'The right to move the Supreme Court by appropriate proceedings for the enforcement of the rights conferred by this Part is guaranteed.',meaning:'A person can approach the Supreme Court through appropriate proceedings to enforce fundamental rights.',note:'A lawyer can help decide the proper forum and remedy; Article 226 concerns High Court writ powers.',keywords:'fundamental rights supreme court writ remedies'},
{id:'bnss38',ref:'BNSS · Section 38',title:'Meet your advocate during questioning',category:'Arrest & procedure',source:'bnss',quote:'to meet an advocate of his choice during interrogation, though not throughout interrogation.',meaning:'If arrested and questioned by police, you are entitled to meet your chosen advocate during interrogation.',note:'The section does not guarantee the advocate’s continuous presence throughout questioning.',keywords:'arrest interrogation lawyer questioning custody police'},
{id:'bnss47',ref:'BNSS · Section 47',title:'Know why you are being arrested',category:'Arrest & procedure',source:'bnss',quote:'forthwith communicate to him full particulars of the offence for which he is arrested or other grounds for such arrest.',meaning:'For an arrest without a warrant, the person making the arrest must promptly explain the offence or other grounds. In the cases covered by subsection (2), police must explain the right to bail.',note:'Bail depends on the offence and applicable law. This is not a guarantee of immediate release.',keywords:'arrest reason grounds warrant bail detention'},
{id:'bnss48',ref:'BNSS · Section 48',title:'Have a relative or friend informed',category:'Arrest & procedure',source:'bnss',quote:'forthwith give the information regarding such arrest and place where the arrested person is being held',meaning:'The person making an arrest must promptly inform a nominated relative, friend or other person about the arrest and where the arrested person is held, and inform the designated district police officer.',note:'Ask for the person you nominate to be informed. The police station must record who was notified.',keywords:'arrest family friend inform relative custody'},
{id:'bnss58',ref:'BNSS · Section 58',title:'The limit on detention without a magistrate',category:'Arrest & procedure',source:'bnss',quote:'twenty-four hours exclusive of the time necessary for the journey from the place of arrest to the Magistrate’s Court',meaning:'For an arrest without warrant, police detention cannot ordinarily exceed 24 hours, excluding necessary travel, without a magistrate’s special order under section 187.',note:'A magistrate can authorise further detention. This does not mean automatic release after 24 hours.',keywords:'arrest 24 hours detention magistrate custody'},
{id:'bnss173',ref:'BNSS · Section 173(1)',title:'Report a cognizable offence',category:'Arrest & procedure',source:'bnss',quote:'irrespective of the area where the offence is committed, may be given orally or by electronic communication',meaning:'Information about a cognizable offence may be given to the officer in charge of a police station regardless of where the offence occurred. Electronic information must be signed within three days to be taken on record.',note:'Often called the Zero FIR framework. Subsection (3) permits a preliminary enquiry in specified cases; not every grievance is a cognizable offence.',keywords:'fir zero fir complaint police report jurisdiction theft crime accident'},
{id:'bnss173copy',ref:'BNSS · Section 173(2)',title:'Receive a free copy of recorded information',category:'Arrest & procedure',source:'bnss',quote:'shall be given forthwith, free of cost, to the informant or the victim.',meaning:'The informant or victim is entitled to a free copy of information recorded under section 173(1).',note:'If the station refuses to record the information, subsection (4) provides escalation to the Superintendent of Police and, if needed, a magistrate.',keywords:'fir copy free complaint refused police sp'},
{id:'bns281',ref:'BNS · Section 281',title:'Rash driving on a public way',category:'Road & medical',source:'bns',quote:'Whoever drives any vehicle, or rides, on any public way in a manner so rash or negligent as to endanger human life',meaning:'Rash or negligent driving on a public way that endangers life or is likely to injure someone can be a criminal offence.',note:'The appropriate offences depend on the evidence and whether hurt, grievous hurt or death resulted. Reporting and compensation are separate processes.',keywords:'accident driving rash negligent car bike road'},
{id:'mv162',ref:'Motor Vehicles Act · Section 162',title:'Cashless treatment scheme framework',category:'Road & medical',source:'mv',quote:'Scheme for golden hour.',meaning:'Section 162 provides the statutory framework for a cashless road-accident treatment scheme. The operational scheme determines coverage and process.',note:'This quote is the official section heading. Ask the hospital about PM RAHAT and designated-hospital eligibility.',keywords:'accident hospital insurance bill treatment golden hour'},
{id:'rahat',ref:'PM RAHAT · Official scheme release',title:'Cashless road-accident treatment',category:'Road & medical',source:'rahat',quote:'cashless treatment up to ₹1.5 lakh per victim, for period of 7 days from the date of accident.',meaning:'Eligible road-accident victims may receive up to ₹1.5 lakh of cashless treatment for seven days. Call 112 for a designated hospital and ambulance assistance.',note:'Eligibility, hospital designation and police authentication apply. Ask the hospital to confirm coverage; this is distinct from your personal insurance policy or a compensation award.',keywords:'accident insurance cashless hospital charges bill pm rahat treatment'},
{id:'mv166',ref:'Motor Vehicles Act · Section 166',title:'Apply for accident compensation',category:'Road & medical',source:'mv',quote:'Application for compensation.',meaning:'Section 166 provides a route to seek compensation before the Motor Accident Claims Tribunal. A lawyer can assess the proper claimant, documents, limitation and applicable compensation route.',note:'This is the official section heading. A police report is not itself a compensation award. Seek advice promptly about deadlines.',keywords:'accident insurance compensation claim tribunal ma ct'},
{id:'ndps50',ref:'NDPS Act · Section 50',title:'Safeguards for personal searches',category:'Special laws',source:'ndps',quote:'Conditions under which search of persons shall be conducted.',meaning:'For personal searches within this section, safeguards concerning a Gazetted Officer or magistrate may apply. Ask your lawyer to examine how the search was conducted.',note:'This is the official heading. The rule concerns searches of persons; its application to bags, vehicles and premises is fact-sensitive. It is not automatic immunity or a basis to resist a lawful search.',keywords:'drugs narcotics ndps ganja cannabis contraband search seized illegal commodity commodities'},
{id:'ndps37',ref:'NDPS Act · Section 37',title:'Special bail restrictions',category:'Special laws',source:'ndps',quote:'Offences to be cognizable and non-bailable.',meaning:'NDPS bail requires careful legal assessment. Additional conditions apply to offences under sections 19, 24 and 27A and offences involving commercial quantity.',note:'Official section heading. The substance, quantity, alleged conduct and other provisions matter. Do not assume all possession cases have identical bail requirements.',keywords:'drugs ndps narcotics bail quantity seized commodities'},
{id:'it66c',ref:'IT Act · Section 66C',title:'Identity theft',category:'Cyber & consumer',source:'it',quote:'electronic signature, password or any other unique identification feature of any other person',meaning:'Fraudulent or dishonest use of someone else’s electronic signature, password or unique identification feature may attract section 66C.',note:'The quote is an excerpt. Preserve transaction references and original messages; report financial cyber fraud promptly on 1930.',keywords:'cyber identity theft password account hacked otp'},
{id:'it66d',ref:'IT Act · Section 66D',title:'Online impersonation fraud',category:'Cyber & consumer',source:'it',quote:'any communication device or computer resource cheats by personation',meaning:'Cheating by impersonation using a communication device or computer resource may attract section 66D.',note:'Not every online dispute is impersonation fraud. Contact your bank and 1930 promptly if money was lost.',keywords:'cyber fraud scam upi digital arrest impersonation money online'},
{id:'dv17',ref:'Domestic Violence Act · Section 17',title:'Residence in a shared household',category:'Family & safety',source:'dv',quote:'Right to reside in a shared household.',meaning:'The Act recognises a woman’s right to reside in a shared household in a domestic relationship, subject to the statutory framework. A Protection Officer or lawyer can help seek appropriate relief.',note:'Official section heading. Residence rights and ownership are different; application depends on the domestic relationship and household facts.',keywords:'domestic violence husband home wife abuse eviction shared household'},
{id:'dv18',ref:'Domestic Violence Act · Section 18',title:'Protection orders',category:'Family & safety',source:'dv',quote:'Protection orders.',meaning:'A magistrate may make protection orders under the Act, including orders addressing domestic violence and prohibited contact, after applying the statutory requirements.',note:'Official section heading. Call 112 for immediate danger. A helpline contact alone does not create a court order.',keywords:'domestic violence abuse protection threat wife partner'},
{id:'consumer35',ref:'Consumer Protection Act · Section 35',title:'File a consumer complaint',category:'Cyber & consumer',source:'consumer',quote:'Manner in which complaint shall be made.',meaning:'The Act sets out who can file a consumer complaint and permits electronic filing as prescribed. NCH can help with a grievance before you consider a consumer commission.',note:'Official section heading. Jurisdiction, filing fees and time limits must be checked for the particular dispute. NCH is a grievance channel, not a court.',keywords:'consumer refund product defective seller shopping delivery service purchase'},
{id:'aid12',ref:'Legal Services Authorities Act · Sections 12–13',title:'Eligibility for free legal aid',category:'Legal aid',source:'aid',quote:'Criteria for giving legal services.',meaning:'Eligibility includes specified groups, such as women, children and persons in custody, as well as people meeting applicable income criteria. The legal services authority assesses the statutory requirements.',note:'Official section 12 heading. Income limits vary by forum and jurisdiction. Contact NALSA or your District Legal Services Authority for assessment.',keywords:'free legal aid lawyer poor income custody women child nalsa'}
];
export const constitutionalLaws = constitutionalEntries as Law[];
export const crimeLaws = crimeEntries as Law[];
export const laws: Law[] = [...baseLaws.map(l=>constitutionalLaws.find(c=>c.id===l.id)||l), ...constitutionalLaws.filter(c=>!baseLaws.some(l=>l.id===c.id))];

export type Guide={id:string;title:string;subtitle:string;keywords:string[];intro:string;steps:string[];documents:string[];lawIds:string[];helpline:string;questions:string[]};
export const guides:Guide[]=[
{id:'accident',title:'Road accident',subtitle:'Treatment & compensation',keywords:['accident','crash','collision','hospital','insurance','road','bike','car','cashless','rahat','दुर्घटना','अस्पताल'],intro:'Get urgent medical help first. Treatment funding, the criminal report and an accident-compensation claim are separate routes.',steps:['Call 112 for emergency assistance and the nearest designated hospital. Do not delay emergency care to collect paperwork.','Ask the hospital’s help desk about PM RAHAT cashless treatment, scheme registration and police authentication. Ask for the eligibility or rejection reason in writing.','Tell police the facts, location, time, vehicle details and injuries. Ask for an acknowledgement and, when recorded, the FIR copy. The police assess the applicable offences.','Keep bills and records. Notify the relevant insurer promptly and ask a lawyer or DLSA about the Motor Accident Claims Tribunal and any filing deadline.'],documents:['Medical and discharge records','Bills, receipts and insurer correspondence','Vehicle / policy details, if known','Police acknowledgement / FIR number','Photos and witness contacts, if safely obtained'],lawIds:['rahat','mv162','bns281','bnss173','mv166'],helpline:'112',questions:['Does the hospital participate in PM RAHAT, and has my case been authenticated?','Which treatment costs are covered, and why is any payment being requested?','Which compensation route and deadline apply to my accident?']},
{id:'arrest',title:'Arrest & questioning',subtitle:'Know your safeguards',keywords:['arrest','police','detained','custody','question','interrogat','bail','lawyer','गिरफ्तार','पुलिस'],intro:'Ask for legal assistance and the reason for the arrest. The applicable procedure depends on the facts and any special law involved.',steps:['Ask which offence or legal ground is being relied on. Note the officer’s identity, station, time and location if you can safely do so.','Ask to consult your lawyer, and ask for a nominated relative or friend to be informed of the arrest and place of detention.','Ask for an explanation of any document before signing it. Request advice about self-incrimination; do not give false information or obstruct lawful procedure.','Tell your lawyer or the magistrate promptly about injuries, medical needs, coercion or procedural concerns. Call 15100 to seek legal aid assistance.'],documents:['Arrest memo or notice, if provided','Station and officer details','Timeline of detention','Medical information and records','Contact details of your lawyer and nominated person'],lawIds:['art20','art22','bnss38','bnss47','bnss48','bnss58','aid12'],helpline:'15100',questions:['Am I being arrested, and under which provisions?','When can I meet my advocate?','Has my nominated person been informed, and which court will hear the matter?']},
{id:'contraband',title:'Seizure or alleged possession',subtitle:'Special laws & legal help',keywords:['drug','ndps','narcotic','ganja','cannabis','weed','contraband','commodity','commodities','seiz','illegal goods','नशीले'],intro:'“Illegal commodities” can fall under different laws. Drug allegations, customs issues, weapons and state excise offences cannot be treated as the same case.',steps:['Ask which Act and sections are alleged and request a lawyer immediately. NDPS guidance below is relevant only if narcotic drugs or psychotropic substances are involved.','Ask about the search and seizure documentation and record objections truthfully through your lawyer. Do not conceal, destroy, move or tamper with evidence.','For a personal search under the NDPS Act, ask your lawyer about section 50 safeguards. Their application depends on the search facts and statutory exceptions.','Ask for a nominated person to be informed if arrested. Have your lawyer check the alleged substance, quantity, search procedure and bail rules; no automatic release is promised.'],documents:['Search / seizure memo, if provided','Notice or arrest documents','Exact Act and section numbers','Substance and quantity alleged by the authorities','Timeline and witness details'],lawIds:['art20','bnss38','bnss47','bnss48','ndps50','ndps37'],helpline:'15100',questions:['Which specific law applies to the goods involved?','Was this a personal search, a bag search, a vehicle search or a premises search?','What quantity is alleged, and which bail provisions apply?']},
{id:'cyber',title:'Online fraud',subtitle:'Report & preserve evidence',keywords:['cyber','fraud','scam','upi','otp','hacked','hack','impersonat','digital arrest','online money','फ्रॉड'],intro:'Act promptly when money is lost online. A complaint can help authorities respond, but recovery is not guaranteed.',steps:['Call 1930 promptly for financial cyber-fraud reporting and contact your bank through its official channel to report the transaction.','Submit the complaint on cybercrime.gov.in and retain your acknowledgement. Follow the instructions given by the reporting channel.','Preserve transaction IDs, original messages, phone numbers and website addresses. Do not delete the originals or pay a “recovery agent”.','Ask police or a lawyer about the applicable offences. The facts may involve impersonation, identity theft or other offences.'],documents:['Bank transaction / UTR references','Date, time and amount of transfers','Original messages and website addresses','Complaint acknowledgement','Bank complaint reference'],lawIds:['it66c','it66d','bnss173','bnss173copy'],helpline:'1930',questions:['Has my bank recorded the disputed transaction?','What follow-up does my complaint acknowledgement require?','Which original records should I preserve for the investigator?']},
{id:'domestic',title:'Safety at home',subtitle:'Protection & support',keywords:['domestic','husband','wife','abuse','partner','violence','home threat','पीड़ित','घरेलू'],intro:'If you are in immediate danger, prioritise reaching a safe place and emergency assistance. Use a safe device if someone monitors your activity.',steps:['Call 112 for immediate danger. Women can also contact 181 for support and referral where the service operates.','Ask a Protection Officer, One Stop Centre or lawyer about available safety support and appropriate orders under the Domestic Violence Act.','Preserve messages and medical records only if safe. Do not put yourself at risk to collect evidence.','Contact NALSA on 15100 about free legal aid and assistance approaching the appropriate authority.'],documents:['A factual incident timeline','Medical records, if any','Messages or photos already safely available','Any existing court orders or complaints','A safe contact method for your lawyer'],lawIds:['dv17','dv18','aid12','bnss173'],helpline:'181',questions:['Where can I access a Protection Officer or One Stop Centre?','Which protection, residence or other relief can I seek?','How can authorities contact me safely?']},
{id:'consumer',title:'Consumer complaint',subtitle:'Purchases, refunds & services',keywords:['consumer','refund','defect','product','seller','purchase','shopping','delivery','warranty','service complaint'],intro:'Keep the transaction record and explain the remedy you are asking for. A consumer grievance and a criminal fraud complaint are different routes.',steps:['Write to the seller or service provider with the transaction details, problem and requested remedy. Keep a copy.','Contact the National Consumer Helpline at 1915 (8 am–8 pm) or use consumerhelpline.gov.in.','Keep all invoices, warranties and correspondence, including the complaint reference and response.','If unresolved, seek advice about the appropriate consumer commission, jurisdiction, limitation and filing requirements.'],documents:['Invoice / order number','Payment proof','Warranty and terms supplied','Photos of the defect, if relevant','Written complaint and seller’s response'],lawIds:['consumer35','aid12'],helpline:'1915',questions:['What remedy should I ask for: repair, replacement, refund or compensation?','Which commission has jurisdiction, and what is the filing deadline?','Have I preserved proof of the complaint and the reply?']},
{id:'fir',title:'Reporting a crime',subtitle:'FIRs & police complaints',keywords:['fir','complaint','stolen','theft','robbery','report crime','refus','zero fir'],intro:'Describe what happened accurately. You do not need to settle the legal charge yourself before reporting the facts.',steps:['Call 112 if there is immediate danger. Otherwise give a factual account to the police station with dates, places and available records.','For a cognizable offence, section 173 permits information irrespective of where it occurred. Electronic information must be signed within three days to be taken on record.','Ask for the free copy of recorded information and keep the acknowledgement. Ask how to follow up.','If the officer refuses to record the information, ask a lawyer about writing to the Superintendent of Police under section 173(4) and, if necessary, applying to the magistrate.'],documents:['A clear chronological account','Available original evidence','Witness contact details','Police acknowledgements','Copies of written submissions'],lawIds:['bnss173','bnss173copy','aid12'],helpline:'15100',questions:['Is this a cognizable offence or a different type of complaint?','What is my acknowledgement or FIR number?','What is the appropriate escalation if recording is refused?']},
{id:'rights',title:'Fundamental rights & legal aid',subtitle:'Constitutional protections',keywords:['constitution','right','equality','discrimination','liberty','fundamental','legal aid','free lawyer','संविधान','अधिकार'],intro:'Constitutional rights are the foundation. The facts, responsible authority and available remedy determine how a legal challenge should be brought.',steps:['Identify the action you want to challenge and the public authority involved. Preserve the order, notice or correspondence.','Write a short timeline and note any immediate hearing or response deadline.','Contact NALSA or your DLSA for legal aid eligibility and appropriate assistance.','Ask a lawyer which right, statute, forum and remedy fit your facts; do not assume every dispute should go directly to the Supreme Court.'],documents:['Order or notice being challenged','Correspondence with the authority','Timeline and deadlines','Relevant records','Eligibility documents requested by the legal aid authority'],lawIds:['art14','art21','art32','aid12'],helpline:'15100',questions:['Which right and remedy are relevant to these facts?','Which court or authority should I approach?','Do I qualify for free legal aid?']}
];
export function matchGuides(text:string){const t=text.toLowerCase();return guides.map(g=>({guide:g,score:g.keywords.reduce((n,k)=>n+((k.length>3?t.includes(k):new RegExp(`\\b${k}\\b`,'i').test(t))?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.guide).slice(0,3)}
export const helplines=[
{number:'112',name:'Emergency response',category:'Emergency',context:'Immediate danger, police, fire or urgent medical assistance. For road accidents, ask for ambulance support and a designated hospital.',hours:'Emergency service',source:'Ministry of Road Transport & Highways / PIB',url:sources.rahat.url},
{number:'15100',name:'National legal aid helpline',category:'Legal aid',context:'Ask NALSA about legal assistance, eligibility and your nearest legal services authority. Not an emergency-dispatch service.',hours:'National toll-free helpline',source:'National Legal Services Authority',url:'https://nalsa.gov.in/faqs/'},
{number:'1930',name:'Financial cyber fraud',category:'Cybercrime',context:'Report financial cyber fraud promptly. Also notify your bank and follow up on the National Cyber Crime Reporting Portal.',hours:'Report as soon as possible',source:'Ministry of Home Affairs / I4C',url:sources.crime.url},
{number:'181',name:'Women’s helpline',category:'Women & children',context:'Support and referral for women facing violence or distress. Availability and local routing may vary; call 112 for immediate danger.',hours:'State-linked support service',source:'Ministry of Women & Child Development',url:'https://spniwcd.wcd.gov.in/'},
{number:'1098',name:'Child helpline',category:'Women & children',context:'Help for a child in distress or needing care and protection. Call 112 for an immediate threat to life.',hours:'Mission Vatsalya',source:'Ministry of Women & Child Development',url:'https://spniwcd.wcd.gov.in/'},
{number:'1915',name:'National Consumer Helpline',category:'Consumer',context:'Consumer grievances involving goods or services, refunds and seller complaints. NCH helps resolve grievances before litigation.',hours:'8 am–8 pm',source:'Department of Consumer Affairs',url:'https://consumerhelpline.gov.in/'}
];
export const officialPortals=[
{name:'India Code',context:'Search central and state Acts, sections, rules and notifications.',url:'https://www.indiacode.nic.in/'},
{name:'Supreme Court of India',context:'Official judgments, orders and case information.',url:'https://www.sci.gov.in/'},
{name:'eCourts Services',context:'Check case status and orders using the court’s official service.',url:'https://services.ecourts.gov.in/'},
{name:'National Judicial Data Grid',context:'Official court pendency and disposal dashboards; pendency is not crime incidence.',url:'https://njdg.ecourts.gov.in/'},
{name:'NALSA directory',context:'Find your State or District Legal Services Authority.',url:'https://nalsa.gov.in/directory/'},
{name:'National Cyber Crime Reporting Portal',context:'Submit and track an online cybercrime complaint.',url:'https://cybercrime.gov.in/'},
{name:'Open Government Data',context:'Government datasets and API access. Dataset release dates and API registration requirements vary.',url:'https://www.data.gov.in/'},
{name:'NCRB',context:'Crime in India publications and official statistical releases.',url:'https://ncrb.gov.in/'}
];
